server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:"siempre coincide con el puerto" /h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true

  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:pagosDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  # ===============================
  # JPA / HIBERNATE esto es solo para etapa de desarrollo
  # ===============================
  jpa:
    show-sql: true
    hibernate:
     #en produccion se utiliza none
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        defer-datasource-initialization: true
     

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"