spring:
  application:
    name: microservicio-pagos
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        uurl: http://localhost/8087
  